brew 'mas'

mas 'Xcode', id: 497799835

brew 'openconnect'
brew 'rabbitmq'
brew 'elasticsearch'
brew 'lua'
cask 'java'
brew 'vim'
brew 'curl'
cask 'iterm2'
cask 'lastpass'
cask 'jetbrains-toolbox'
cask 'keybase'
cask 'Hammerspoon'
cask 'spotify'
cask 'google-chrome'
cask 'skype'
cask 'dropbox'
cask 'Wavebox'
cask 'virtualbox'
cask 'plex-media-player'
