monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-iFi_*"
      }
    ]
    actions = {
      update-props = {
        device.profile = "pro-audio"
      }
    }
  }
]
