monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.usb-iFi_*"
      }
    ]
    actions = {
      update-props = {
        # Higher priority so the iFi becomes default sink when connected
        priority.session = 2000
      }
    }
  }
]
