# QBZ DAC Setup - ACP/ACP3X/ACP6x Audio Coprocessor Speaker
monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_output.pci-0000_c5_00.5-platform-amd_sdw.HiFi__Speaker__sink", media.class = "Audio/Sink" }
    ]
    actions = {
      update-props = {
        audio.allowed-rates = [ 44100 48000 88200 96000 176400 192000 ]
        resample.disable = true
        channelmix.disable = true
      }
    }
  }
]
