font_family JetBrainsMono Nerd Font
# bold_font   JetbrainsMono Nerd Font Mono Bold
# italic_font JetbrainsMono Nerd Font Mono Italic

#font_family monospace
#bold_font auto
#italic_font auto
#bold_italic_font auto

include ./themes/themes/Kanagawa.conf
hide_window_decorations True
dynamic_background_opacity yes
background_opacity 0.95

#Map ctrl-backspace to backwards delete word: https://github.com/kovidgoyal/kitty/discussions/3286#discussioncomment-520290
#Doesn't seem to work with zsh-vi-mode?
map ctrl+backspace send_text all \x17

