font_family JetBrainsMono Nerd Font
# bold_font   JetbrainsMono Nerd Font Mono Bold
# italic_font JetbrainsMono Nerd Font Mono Italic

#font_family monospace
#bold_font auto
#italic_font auto
#bold_italic_font auto

include ./themes/themes/ayu.conf
hide_window_decorations True
background_opacity 0.8
dynamic_background_opacity yes


