#!/usr/bin/env bash

#Install caps2esc to modify caps lock to be escape on short press,
# Ctrl on keychording
# Seems to work under both Wayland and X11 and does not require xcape or gnome-tweaks

# install build deps
sudo apt install libudev-dev libyaml-cpp-dev libevdev-dev cmake

# create a folder where to clone the source code
# clone the necessary code

clone git@gitlab.com:interception/linux/tools.git
clone git@gitlab.com:interception/linux/plugins/caps2esc.git
# build and install the interception framework
BASE_DIR="~/src/git/gitlab.com/interception/linux/"
$BASE_DIR/tools/
mkdir $BASE_DIR/tools/build
cd $BASE_DIR/tools/build
cmake $BASE_DIR/tools
make
sudo make install
# build the caps2esc plugin
cd $BASE_DIR/plugins/caps2esc
make && sudo make install

echo "Copying config files"
sudo cp -f $DOTFILES_PATH/script/udevmon.yaml /etc/
sudo cp -f $DOTFILES_PATH/script/udevmon.service /etc/systemd/system/udevmon.service 

echo "Enabling systemd udevmon service"
sudo systemctl enable --now udevmon

