#!/usr/bin/env bash
which keybase > /dev/null || brew cask install keybase
keybase login
SECRETS_DIR="$HOME/src/git/keybase/secrets"
if [ ! -d "$SECRETS_DIR" ];
then
  git clone keybase://private/herder/secrets $SECRETS_DIR
fi
chmod -r 0400 $SECRETS_DIR/.ssh/
